TrainerGrove_MapScripts::
	.byte 0


TrainerGrove_EventScript_TrainerOne::
# 6 "data/maps/TrainerGrove/scripts.pory"
	trainerbattle_single TRAINER_TRAINERGROVET1, TrainerGrove_Text_Trainer1Intro, TrainerGrove_Text_Trainer1Outro
	end


TrainerGrove_EventScript_TrainerTwo::
# 11 "data/maps/TrainerGrove/scripts.pory"
	trainerbattle_single TRAINER_TRAINERGROVET2, TrainerGrove_Text_Trainer2Intro, TrainerGrove_Text_Trainer2Outro
	end


TrainerGrove_EventScript_TrainerThree::
# 16 "data/maps/TrainerGrove/scripts.pory"
	trainerbattle_single TRAINER_TRAINERGROVET3, TrainerGrove_Text_Trainer3Intro, TrainerGrove_Text_Trainer3Outro
	end


TrainerGrove_EventScript_TrainerFour::
# 21 "data/maps/TrainerGrove/scripts.pory"
	trainerbattle_single TRAINER_TRAINERGROVET4, TrainerGrove_Text_Trainer4Intro, TrainerGrove_Text_Trainer4Outro
	end


TrainerGrove_Text_Trainer1Intro::
# 25 "data/maps/TrainerGrove/scripts.pory"
	.string "Bring that ass here boy!$"

TrainerGrove_Text_Trainer1Outro::
# 29 "data/maps/TrainerGrove/scripts.pory"
	.string "Your gyatt was too much for me to handle.$"

TrainerGrove_Text_Trainer2Intro::
# 33 "data/maps/TrainerGrove/scripts.pory"
	.string "Uhh I think I'm in the wrong place.$"

TrainerGrove_Text_Trainer2Outro::
# 37 "data/maps/TrainerGrove/scripts.pory"
	.string "Damn, could you at least get me unstuck stepbro?$"

TrainerGrove_Text_Trainer3Intro::
# 41 "data/maps/TrainerGrove/scripts.pory"
	.string "IMA BOUNCE ON YOU!$"

TrainerGrove_Text_Trainer3Outro::
# 45 "data/maps/TrainerGrove/scripts.pory"
	.string "This champ sucks, I'ma play Nunu instead.$"

TrainerGrove_Text_Trainer4Intro::
# 49 "data/maps/TrainerGrove/scripts.pory"
	.string "Your gyat is gonna get rizzled.$"

TrainerGrove_Text_Trainer4Outro::
# 53 "data/maps/TrainerGrove/scripts.pory"
	.string "After this loss, I'm going to Ohio.$"
